"""Adicionando Enterprisem, Product e Imagem ao banco

Revision ID: 32e29bcbd5d1
Revises: 0a49320ba2ba
Create Date: 2026-05-27 22:54:06.316376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e29bcbd5d1'
down_revision: Union[str, Sequence[str], None] = '0a49320ba2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_est', sa.String(length=20), nullable=False),
    sa.Column('cnpj_est', sa.String(length=20), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('whastapp', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('bg_color', sa.String(length=7), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=False),
    sa.Column('banner_path', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('enterprise_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('users', schema=None) as bach_op:
        bach_op.create_foreign_key('fk_users_enterprise', 'enterprises', ['enterprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'enterprise_id')
    op.drop_table('images')
    op.drop_table('products')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
