"""Alterado o image_ref para image no Model Product

Revision ID: 4c6ab84da73b
Revises: 32e29bcbd5d1
Create Date: 2026-05-30 18:36:46.177767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6ab84da73b'
down_revision: Union[str, Sequence[str], None] = '32e29bcbd5d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
