"""Atualizando colunas

Revision ID: 84a01f7f39f2
Revises: 4c6ab84da73b
Create Date: 2026-05-30 18:58:20.031167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a01f7f39f2'
down_revision: Union[str, Sequence[str], None] = '4c6ab84da73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('whatsapp', sa.String(length=20), nullable=False))
    op.drop_column('enterprises', 'whastapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('whastapp', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('enterprises', 'whatsapp')
    # ### end Alembic commands ###
