"""torna logo e banner opcionais em Enterprise

Revision ID: d72f6c69c2d6
Revises: 84a01f7f39f2
Create Date: 2026-05-30 19:02:11.940129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72f6c69c2d6'
down_revision: Union[str, Sequence[str], None] = '84a01f7f39f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprises') as batch_op:
        batch_op.alter_column('logo_path', existing_type=sa.String(length=255), nullable=True)
        batch_op.alter_column('banner_path', existing_type=sa.String(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprises') as batch_op:
        batch_op.alter_column('logo_path', existing_type=sa.String(length=255), nullable=False)
        batch_op.alter_column('banner_path', existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###
